### ISSUE TITLE
Step by Step?

### ISSUE THREAD

**Issue by brianm** [kelseyhightower/standalone-kubelet-tutorial#1]
This is great, I'd *love* a walkthrough on doing it manually from Kubelet to grok how it works, and be able to set it up outside coreos :-)

**Comment by kelseyhightower** [comment]
@brianm Install the kubelet binary and use the same flags.

**Comment by brianm** [comment]
hah, fair enough. Was digging through kubelet-wrapper and the rkt image to map things.

**Comment by brianm** [comment]
Okay, [approximated this](https://gist.github.com/brianm/b560188bdb8adb58796a2aa3322d2394) via hyperkube, and using the host network & friends :-)
